apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:

  - http:
      paths:
      - path: /app1
        backend:
          serviceName: appweb1
          servicePort: 80
      - path: /app2
        backend:
          serviceName: appweb2
          servicePort: 80