apiVersion: v1
kind: Service
metadata:
  name: appweb1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: appweb1
---
apiVersion: v1
kind: Service
metadata:
  name: appweb2
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector: 
    app: appweb2
  